### PR TITLE
LevelDB update to v1.22

### PR DESCRIPTION
**Pull request by braydonf**

### CODE REVIEW

**Comment by braydonf** [comment]
I think we can hold off on this update until later, however I'll leave this open as example on what is necessary to upgrade, when ready.

**Comment by tynes** [comment]
I didn't realize that you had an open PR for this @braydonf 

I think this is more important after seeing a bug in v1.20 about keys being lost during compaction.
See https://github.com/google/leveldb/pull/339

This is a good precursor to make sure that it still builds on Windows https://github.com/bcoin-org/bdb/pull/11

See my branch here:
https://github.com/tynes/bdb/tree/leveldb-1.22

**Comment by braydonf** [comment]
I was about to reply in the other thread. Yeah I started this when investigating segmentation fault issues (with the bindings) that have since been fixed. Leveldown (upstream) still hasn't upgraded, however Bitcoin Core has [as part](https://github.com/bitcoin/bitcoin/pull/17398) of the latest release candidate.

**Comment by tynes** [comment]
I have a logfile of a bcoin sync with LevelDB 1.20 and another with 1.22, I'd like to dig into them to see if there were any major differences. I also think it would be straightforward to write a benchmark that indexes and reads a bunch of data in a deterministic way to see if there are performance differences.

Once I have it building on Windows (thanks for the merge here https://github.com/bcoin-org/bdb/pull/11), I'll revisit this PR. I feel a lot more comfortable upgrading to 1.22 if Bitcoin Core is also planning on doing so.

**Pull request closed without merging**
